### ISSUE TITLE
Running level-up in Azure

### ISSUE THREAD

**Issue by DinisCruz** [Level/levelup#287]
As anybody managed to make it work?

I tried earlier today and had a bunch of of errors

**Comment by nrkn** [comment]
We're also having had a lot of trouble with levelup+azure

Our previous problem was that for some reason the npm install during azure deployment was getting the wrong leveldown binary - on my local machine leveldown.node was 421kb but the version on the azure deployment was 315kb - this caused the following error:

`Unaught exception: Error: A dynamic link library (DLL) initialization routine failed.`

We were working around this by replacing the 315kb binary with the a copy of the 421kb version post-deployment, once this was done our app ran fine on azure

Today I updated levelup & leveldown to the newest versions, and now the leveldown binary always seems to be the 421kb version, so that issue has gone away, but I get:

`LevelUPError: Failed to require LevelDOWN (Module version mismatch. Expected 47, got 46.)`

I have had no problems using it on my Windows dev box locally however. Same node/npm versions as the azure deployment.

Please let me know if there is any additional information I can provide

**Comment by nrkn** [comment]
I strongly suspect that this is an azure issue and not a levelup issue btw, but thought it would be good to comment just in case

**Comment by ralphtheninja** [comment]
> LevelUPError: Failed to require LevelDOWN (Module version mismatch. Expected 47, got 46.)

This error means node expects leveldown to be compiled for node 5 (abi 47) but the binary was compiled for node 4 (abi 46). It happens if you install something and then upgrade node and then try to run again, so if node has been changed it has to be reinstalled.

**Comment by juliangruber** [comment]
you can give https://github.com/juliangruber/require-rebuild, it will try dynamically rebuilding leveldown in the cloud

**Comment by ralphtheninja** [comment]
> you can give https://github.com/juliangruber/require-rebuild, it will try dynamically rebuilding leveldown in the cloud

+1

**Comment by nrkn** [comment]
The Azure issue when deploying with continuous integration via git seems to be that it keeps no-longer used files from the previous deployment, so after a package upgrade the node module system is finding old versions lying around and using them despite the presence of newer ones :/

**Comment by ralphtheninja** [comment]
> The Azure issue when deploying with continuous integration via git seems to be that it keeps no-longer used files from the previous deployment, so after a package upgrade the node module system is finding old versions lying around and using them despite the presence of newer ones :/

:no_good:
