### ISSUE TITLE
move encodings into leveldown

### ISSUE THREAD

**Issue by dominictarr** [Level/levelup#365]
from discussion on this twitter thread: https://twitter.com/jedschmidt/status/646679054326865920

what would be the pros and cons of just removing encodings from levelup entirely, and making that just something that happens in leveldown? This would allow some backends to use native support for this,
and does anyone _really_ use different encodings for different keys? That would be a huge headache.

This would be a breaking change for all my stuff, in that I'd have to update that code, but it wouldn't break the design because I have never used more than one encoding anyway.

This would be a huge breaking change, but would also simplify a lot, killing loads of code.

I'm not proposing this as a serious change right now, but I do think this would be a possibility that is worth discussing.

**Comment by juliangruber** [comment]
for reference, encodings could be handled inside a leveldown, or inside a "fake" leveldown, like so:

```js
var db = leveldown('./db')
db = encode('buffer', db)
db = levelup(db)

// or

var db = levelup(encode('buffer', leveldown('./db')))
```

**Comment by juliangruber** [comment]
also, we have a `v2` branch already with a couple breaking changes, so this change could fit in there

**Comment by juliangruber** [comment]
also +1 for dropping `.{key,value}Encoding` from any operation exposed in levelup

**Comment by mcollina** [comment]
I'm :+1: for having a single encoding for each database. We should support different encodings for keys and values.

For this to happen, I think we need:

1. an easy way for adding custom encodings to the current *down implementations, possibly as part as levelup api (in the constructor options)
2. a strategy to maintain the current 1.x.x series for 6-12 months (leveldown nan bumps)

**Comment by jcrugzz** [comment]
I'm ok with this. The most I've used encoding wise is `utf8` and `json` values but they were in separate `sublevels` using @mafintosh's `subleveldown`. If my understanding is correct, since `subleveldown` wraps each `sublevel` with a `leveldown`, this will work as expected. The API just might have to change internally slightly.

**Comment by juliangruber** [comment]
pull request: https://github.com/Level/levelup/pull/367

**Comment by ralphtheninja** [comment]
I'm in huge favour of going in this direction and see several advantages:

* simplified code base -> a lot less can go wrong which means less bugs and less work to maintain it, increased readability and all that good stuff
* levelup assumes less -> leveldowns have more freedom to do what they want as long as they support the tests of abstract-leveldown
* levelup can be *done*
* potentially also improvements to performance since encodings could also be pushed to the c++ layer (if there is one obviously)

**Comment by dominictarr** [comment]
I think we'd still support the `level({{key,value}Encoding: ...})` api, for the legacy case where level creates the leveldown instance and passes it to levelup. In cases where you pass a live leveldown to levelup, you'd be required to initialize the leveldown your self.

@mcollina to realize your backcompat via optional encodings idea, it's already pretty easy to add an optional encoding... but I fear this would add additional complexity, rather than remove it. I suspect it would be easier to backport any important patches to the current major version (which would be the previous version, if we made this change) rather than trying to maintain support for them.
Judging from the history of level, the chance of actually having to add a patch like this would be pretty small.

**Comment by juliangruber** [comment]
I wrote the poc encoding wrapper: https://github.com/juliangruber/encoding-down

It's not complete yet, and I'm having trouble setting up a real benchmark suite: https://github.com/juliangruber/encoding-down/issues/2
