### ISSUE TITLE
Question: is it possible to implement atomic increase

### ISSUE THREAD

**Issue by aunz** [Level/levelup#381]
I understand that `db.batch()` can be used for an atomic operation.
However, how to perform an atomic increase, such as 

``` js
db.put('foo', 1)
// then
db.inc('foo', 1)
db.get('foo') // -> 2
```

As opposed to 

``` js
db.put('foo', 1)
db.get('foo', (err, value) => db.put('foo', value + 1))
// but this is not atomic because the value could have changed after the callback
```

Thanks a lot

**Comment by dominictarr** [comment]
batch only gives you an atomic write.

you'd have to create some sort of locking thing because you have to the get is async, and other writes could happen in that time. there have been several approaches to this...

here are two that I could think of off the top of my head:
https://github.com/mikeal/level-mutex
https://github.com/dominictarr/level-update

I havn't seen any that are really satisifying though

**Comment by aunz** [comment]
Thanks Dominic, 
I have looked at your level-update, but if an app is deployed using more than one node clusters, the lock will not work?

**Comment by dominictarr** [comment]
@aunz that is correct. you'd need to have at least part of the database be a centralized process, or use a leader election protocol like raft or paxos.
