### ISSUE TITLE
Parameter sanity checking: 

### ISSUE THREAD

**Issue by martinheidegger** [Level/levelup#406]
Through a bug search in https://github.com/Level/leveldown/issues/314#issuecomment-253770241 I found out that `callback` is not sanity checked and thus an error occured if a value other than a function is passed-in: [`lib/levelup.js#L34`](https://github.com/Level/levelup/blob/90a4c5b45aecc8258f6277e9a0c5c48afcc09511/lib/levelup.js#L34)

A random exception is thrown with a missing callback:

```
/Users/michaelnisi/node_modules/levelup/lib/levelup.js:284
        callback()
        ^

TypeError: callback is not a function
    at /Users/michaelnisi/node_modules/levelup/lib/levelup.js:284:9
```

In order to provide a PR that handles this wrong argument I think it would be important to know if you its better that:
1. No error or warning should be shown if an argument could be resulting in an error _(the argument is ignored)_
2. An error should be immediately thrown when the argument could be resulting in an error
3. The requested command should not be executed but instead return to the callback with an error that contains informations regarding the invalid argument.
4. Current behaviour: fail loudly.

**Comment by ralphtheninja** [comment]
I vote for the second option.

**Comment by michaelnisi** [comment]
Thanks for opening this for discussion, but I think it's already as clear as it gets: 

*the callback in line 284 of levelup.js is not a function*

I'm against these kinds of guards, because, in my opinion, they tend to make code more opaque and thus harder to understand and debug. If the faulty operation isn't harmful, **let it crash!** 💥

Consequently, I'm for the first or, if you can't help yourself, the second option.

**Comment by martinheidegger** [comment]
@michaelnisi I realised that I didn't properly express the options. I added 4) to make it clearer.

**Comment by juliangruber** [comment]
I agree with the other maintainers, this is a pretty useful error to get
