### ISSUE TITLE
Revive create-stream-vs-put-racecondition.js test

### ISSUE THREAD

**Issue by MeirionHughes** [Level/levelup#497]
`create-stream-vs-put-racecondition.js` isn't executed in the test because the runner looks for *-test.js.

It was the same before the changes to allow the typescript to run each test:

levelup/buster.js Line 5 in e152d83
```
tests: [ 'test/*-test.js' ],
```

If you add `-test` to the end, and use  `levelup(leveldown(location))` instead of `levelup(location)`, it fails.

**Comment by vweevers** [comment]
@ralphtheninja want to include this in v2? I can take a look if you want

**Comment by vweevers** [comment]
This might actually be a bug in `deferred-leveldown`. Because on open, [it](https://github.com/Level/deferred-leveldown/blob/4c57e7be86a022ca2bc0170419222e00661b7c51/deferred-leveldown.js#L18) processes queued write operations *before* creating queued iterators.

Essentially, if you create a read stream before the store was opened, you don't get snapshot guarantees.

cc @juliangruber

**Comment by vweevers** [comment]
Did this ever work?

**Comment by vweevers** [comment]
To clarify: the current behavior of *internally* queued write operations in JS-land is counterintuitive to the C++ guarantee that you'll be reading from a snapshot. Writes after a read stream should not be included in the results of the stream.

**Comment by vweevers** [comment]
Confirmed, the test passes when I reorder these lines in `deferred-leveldown` from

```js
self._operations.forEach(function (op) {
  self._db[op.method].apply(self._db, op.args)
})
self._operations = []

self._iterators.forEach(function (it) {
  it.setDb(self._db)
})
self._iterators = []
```

To:

```js
self._iterators.forEach(function (it) {
  it.setDb(self._db)
})
self._iterators = []

self._operations.forEach(function (op) {
  self._db[op.method].apply(self._db, op.args)
})
self._operations = []
```

This breaks [another test](https://github.com/Level/levelup/blob/a5dc8588c253d0a97032a225288eeed8830692de/test/leveldown-substitution-test.js#L16) though, but that might be due to the fact that the test dangerously relies on memdown being synchronous internally.

**Comment by ralphtheninja** [comment]
So what should we do about this? Was this a problem _before_ pulling in `deferred-leveldown@2`? Can we release `levelup@2.0.0` and fix this later or should we address it now?

**Comment by vweevers** [comment]
> So what should we do about this?

I'm not sure yet, trying to think of adverse effects of https://github.com/Level/levelup/issues/497#issuecomment-335015423.

> Was this a problem before pulling in deferred-leveldown@2?

Yes, AFAICT. This has been the case since Level/deferred-leveldown#6 (0.3.0) and Level/levelup#320. Before those PRs, iterators were handled in a different way. They simply waited for `db.once('ready')`, which I'm guessing means it didn't have the problem described above.

> Can we release levelup@2.0.0 and fix this later or should we address it now?

This is another one of those issues that hasn't bitten anyone yet, and the test was *never* enabled I think.

**Comment by vweevers** [comment]
Perhaps a git bisect is in order

**Comment by vweevers** [comment]
Ah, it was *intended* as a failing test. That's what I gather from #128, and from running the test on the commit that introduced it (1cf0655606dfa51f7ba567aa8fa8c191bf6fec8c). Many internals have changed since then, so it's probably senseless to try and compare the current situation with #128. 

However, the internals are also a lot cleaner today, so we have a better chance of fixing it without side effects.

@ralphtheninja no need to include in 2.0.0. We can let this issue simmer for a bit.

**Comment by ralphtheninja** [comment]
Then I want to release 2.0.0 tomorrow. Sounds good?

cc @juliangruber

**Comment by vweevers** [comment]
👍 👍
