### ISSUE TITLE
Buffer returned when String inserted

### ISSUE THREAD

**Issue by mmick66** [Level/levelup#527]
I have this really weird bug in the most simple code:

```
var levelup = require('levelup');
var leveldown = require('leveldown');

let key = 'Michael';
let id = 'id';

var db = levelup(leveldown('./mydb'));
console.log('put', '(' + (typeof key) + ')', key);
db.put(id, key).then((err) => {
    if (err) throw new Error(err);
    db.get(id).then((val) => {
      console.log('get', '(' + typeof val + ')', val);
    });
});
```

I am expecting to get a string but here are the results when I run the file:

```
> node index.js
put (string) Michael
get (object) <Buffer 4d 69 63 68 61 65 6c>
```

The returned value is binary data. The correct data by the way, but the wrong type... What could be going on?!

**Comment by vweevers** [comment]
This is expected behavior, as leveldown returns data as a Buffer by default.

You have three options.

1. Wrap leveldown with [encoding-down](https://github.com/level/encoding-down#usage) (which, with the default options, will always return data as strings)
2. Use [level](https://github.com/Level/level) which conveniently bundles levelup+leveldown+encoding-down
3. If you want to keep your current setup, use the `asBuffer` option on `get()`:

```js
db.get(id, { asBuffer: false }, callback)
```

**Comment by mmick66** [comment]
Thank you!

**Comment by genisgetman** [comment]
This options describes in leveldown README
