### ISSUE TITLE
how can I use filters in leveldb

### ISSUE THREAD

**Issue by pokal4u** [Level/levelup#544]
HI,
How can I use filters in leveldb

Ex: key and values stored like:
registration :
user_1=>"srinivas"
user_2=>"srinivas1"
user_3=>"srinivas2"
user_4=>"srinivas3"
.....

blocked :
blosk_2=>"srinivas1"
block_4=>"srinivas3"

Now I need to display registration users not in blocklist like:
user_1=>"srinivas"
user_3=>"srinivas2"

Please suggest me.

Thanks

**Comment by Leland-Kwong** [comment]
Keys are sorted lexicographically, so you can use 
```
const options = { gte: 'user_', lte: 'user_~' };
db.createReadStream(options)
stream.on('data', callback)
```

The trick is to use the '~' character since it has a high character code.

**Comment by vweevers** [comment]
To add to that, if you want to intersect two sets (like users and blocked users), you can:

1. Use a different key prefix for each set
2. Use e.g. a user id as suffix, so that the two sets sort the same
3. Create two streams, using range options as described by @Leland-Kwong 
4. Pipe both streams into a module like [sorted-intersect-stream](https://github.com/mafintosh/sorted-intersect-stream). It's readme has [a LevelDB example](https://github.com/mafintosh/sorted-intersect-stream#intersecting-leveldb-streams).

To avoid managing prefixes, you can use [`subleveldown`](https://github.com/Level/subleveldown). In fact, with `subleveldown` you wouldn't have to specify range options either!
