### ISSUE TITLE
release levelup

### ISSUE THREAD

**Issue by ralphtheninja** [Level/levelup#549]
So, the big question is .. major, minor or patch? :)

**Comment by ralphtheninja** [comment]
@vweevers If we look at the [Unreleased] section in the changelog, it seems to me we can release a new patch version. WDYT?

**Comment by vweevers** [comment]
Due to the breaking change in `abtract-leveldown` and hence `deferred-leveldown`, doing `db.batch([null])` would theoretically throw, but it already would in `levelup` because of this code:

https://github.com/Level/levelup/blob/85d9bb104fd545738ad8d2cc7e2936c76dafb68f/lib/levelup.js#L259-L262

So yes, a patch is fine.

And when we finish #528, that can also be released as a patch, since it would still throw, just from a different place and with a different message.

**Comment by vweevers** [comment]
@ralphtheninja did you look into https://github.com/Level/levelup/pull/547#issuecomment-364761938?

**Comment by vweevers** [comment]
Ah that's just a test reaching into memdown internals that no longer exist (`_store`):

https://github.com/Level/levelup/blob/2f1ed67efd2430a9387c9041da4b9317f3b279ea/test/leveldown-substitution-test.js#L49-L52

So not a blocker for release.

**Comment by ralphtheninja** [comment]
@vweevers We should rewrite that test though.

**Comment by vweevers** [comment]
Agreed, it can use `memdown.iterator()` to collect the keys.

**Comment by ralphtheninja** [comment]
@vweevers I'm a bit confused, why did that fail in the first place? The tests are passing now.

**Comment by ralphtheninja** [comment]
Ignore me :smile:

**Comment by ralphtheninja** [comment]
Ok, so I'll release a patch now and we can take care of #528 and the memdown.iterator() thing after that.

**Comment by ralphtheninja** [comment]
2.0.2

**Comment by ralphtheninja** [comment]
@vweevers I think we should remove the test using the internals of memdown. I don't see the point of it. The test is already doing `db.createReadStream()` and tests that `entries` is the same as `expected`.

**Comment by ralphtheninja** [comment]
Nevermind. I wrote something anyway.
