### ISSUE TITLE
i don't know key, but value, how to  remove data from the store?

### ISSUE THREAD

**Issue by anlexN** [Level/levelup#585]
i use levelup and leveldown

**Comment by vweevers** [comment]
Can you please provide more context?

**Comment by vweevers** [comment]
If the need to delete a value is a frequent occurrence, I suggest building an inverted index (mapping values to keys).

**Comment by anlexN** [comment]
@ralphtheninja , i think it is not perfect solution. have you try like your says? how much big data, how much time spend.
@vweevers , what is inverted index? i don't review this api in the repo README! where?

**Comment by vweevers** [comment]
> what is inverted index?

https://en.wikipedia.org/wiki/Inverted_index

> i don't review this api in the repo README! where?

It's something that can be built on top of levelup. There are various modules available:

- https://github.com/dominictarr/level-inverted-index
- https://github.com/dominictarr/level-map-merge
- https://github.com/rvagg/node-level-mapped-index
- https://github.com/eugeneware/level-queryengine
- https://github.com/ryanramage/map-reduce-chained
- https://github.com/eugeneware/path-engine
- https://github.com/eugeneware/subindex
- https://github.com/kordon/inverted
- https://github.com/juliangruber/level-sec
- https://github.com/juliangruber/level-secondary

**Comment by ralphtheninja** [comment]
@vweevers Are we linking to some of these from our awesome repo?

**Comment by vweevers** [comment]
Not yet: https://github.com/Level/awesome/issues/1#issuecomment-334735746

**Comment by anlexN** [comment]
i don't like any other modules. because those are not often maintained frequently. why not be implemented natively in the level?

**Comment by vweevers** [comment]
@anlexN level is a small yet powerful key-value store. It is not a full-featured database with indexing features and the like, because that often means including features people don't need - or worse, including opinionated features that people cannot modify to suit *their* needs.

About the benefits of modularity:

- http://mafintosh.com/pragmatic-modularity.html#lower-level-is-better-than-higher-level
- https://gist.github.com/substack/5075355
- https://gist.github.com/substack/68f8d502be42d5cd4942#gistcomment-1365106

> i don't like any other modules.

Not *any* of them? You're missing out! Check out some of those modules, see how they work, what works for you. And of course, nothing is stopping you from helping out or writing your own :)
