### ISSUE TITLE
Get `leveldb.BytewiseComparator` error

### ISSUE THREAD

**Issue by zhaoyi0113** [Level/levelup#647]
I coped a database from Android device and run it on MacOS.

When I run `db.isOpen()` I got below error:

`
OpenError: Invalid argument: idb_cmp1 does not match existing comparator : leveldb.BytewiseComparator`

How does `levelup` support Bytewise?

**Comment by vweevers** [comment]
It's the other way around. The default LevelDB comparator is bytewise, your data used `idb_cmp1` which is Google's IndexedDB comparator and a bit more complicated.

**Comment by vweevers** [comment]
To expand a bit: there's currently no way to read this particular database. You'll need to implement Google's IndexedDB comparator in `leveldown` (C++) which currently doesn't expose a way to override the default bytewise comparator.

If you need help (I'm sure other people will be interested in this as well!) feel free to open a new issue in either [`community`](https://github.com/Level/community) (because this effort might span multiple projects) or [`leveldown`](https://github.com/Level/leveldown). ❤️
