### ISSUE TITLE
Implementing transaction on top of LevelUp?

### ISSUE THREAD

**Issue by endyjasmi** [Level/levelup#691]
Hello, I am currently implementing a document engine on top LevelUp with support for transaction. The transaction implementation is greatly inspired by [this article](https://ongardie.net/blog/node-leveldb-transactions/) from 2015. Sadly there is no way to follow down that path as currently LevelUp does not support snapshot.

1. I am wondering if there's a plan to implement snapshot feature?
2. If not, if there's a plan to implement `.prev` method on the LevelDown iterator?
3. If not, if there is other method of implementing transaction on top of LevelUp?

The reason I am sticking with LevelUp is because I need the document engine to runs on browser also on nodejs (that rule's out sqlite).

Thanks in advance.

**Comment by vweevers** [comment]
> 1. I am wondering if there's a plan to implement snapshot feature?

Iterators do operate on a snapshot; if that isn't sufficient see https://github.com/Level/community/issues/47 (TLDR: we need a good use case and a good API).

> 2. If not, if there's a plan to implement .prev method on the LevelDown iterator?

See https://github.com/Level/abstract-leveldown/issues/339 and https://github.com/Level/leveldown/issues/646.

> 3. If not, if there is other method of implementing transaction on top of LevelUp?

Various people have attempted it: https://github.com/Level/awesome#atomicity

> I need the document engine to runs on browser also on nodejs (that rule's out sqlite).

In that case, exposing a snapshot can't be done, because IndexedDB doesn't have the necessary primitives.

**Comment by endyjasmi** [comment]
Well, thank you for reply. I'll explore the links you shared. Worst come to worse, maybe I'll implement on top of sqlite for nodejs and indexeddb for browser but it's going to take twice the work and I am reluctant to do it.

Anyway, thanks once again.
